format = """
[](purple)\
$username\
[](bg:pink fg:purple)\
$directory\
[](bg:background fg:pink)\
$all
"""

add_newline = false

palette = "dracula"

[aws]
style = "bold orange"

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold green)"

[cmd_duration]
style = "bold yellow"

[git_branch]
style = "bold pink"

[git_status]
style = "bold red"

[hostname]
style = "bold purple"

[username]
format = "[ $user ]($style)"
style_user = "bg:purple fg:background"
style_root = "bg:purple fg:background"
show_always = true

[directory]
format = "[ $path ]($style)"
style = "bg:pink fg:background"
truncation_length = 3
truncation_symbol = "…/"

[time]
format = "[$time]($style)"
style = "bold pink"
disabled = false


# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
