format = """
[](fg:lavender)\
$shell\
[](bg:blue fg:lavender)\
$username\
$hostname\
[](bg:sapphire fg:blue)\
$time\
[](bg:sky fg:sapphire)\
$directory\
[](bg:green fg:sky)\
$git_branch\
$git_status\
$git_state\
[](fg:green)\
$line_break\
$character
"""

add_newline = false

palette = "catppuccin_mocha"

[aws]
style = "bold orange"

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[cmd_duration]
style = "bold yellow"

[git_branch]
style = "bg:green fg:bold crust"
format = "[ $branch(:$remote_branch) ]($style)"

[git_status]
style = "bg:green fg:bold crust"
format = "([$all_status$ahead_behind]($style))"

[username]
format = "[ $user]($style)"
style_user = "bg:blue fg:bold crust"
style_root = "bg:blue fg:bold crust"
show_always = true

[hostname]
format = "[@]($style)[$hostname ]($style)"
style = "bg:blue fg:bold crust"
ssh_only = false
disabled = false

[shell]
format = "[ $indicator ]($style)"
style = "bg:lavender fg:bold crust"
bash_indicator = "#"
fish_indicator = "󰈺"
nu_indicator = "_"
zsh_indicator = ""
disabled = false

[directory]
format = "[ $path ]($style)"
style = "bg:sky fg:bold crust"
truncation_length = 3
truncation_symbol = "…/"

[time]
format = "[ $time ]($style)"
style = "bg:sapphire fg:bold crust"
time_format = "%R"
disabled = false

[custom.time]
command = 'date +%R'
format = '[](fg:lavender)[$output]($style)[](fg:lavender) -> '
style = "bg:lavender fg:bold crust"
when = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
